// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package githubgraphql

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type GraphQLClient interface {
	GetPullRequestAuthor(ctx context.Context, owner string, name string, number int, interceptors ...clientv2.RequestInterceptor) (*GetPullRequestAuthor, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) GraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetPullRequestAuthor_Repository_PullRequest_Author struct {
	Login string "json:\"login\" graphql:\"login\""
}

func (t *GetPullRequestAuthor_Repository_PullRequest_Author) GetLogin() string {
	if t == nil {
		t = &GetPullRequestAuthor_Repository_PullRequest_Author{}
	}
	return t.Login
}

type GetPullRequestAuthor_Repository_PullRequest struct {
	Author *GetPullRequestAuthor_Repository_PullRequest_Author "json:\"author,omitempty\" graphql:\"author\""
	Title  string                                              "json:\"title\" graphql:\"title\""
}

func (t *GetPullRequestAuthor_Repository_PullRequest) GetAuthor() *GetPullRequestAuthor_Repository_PullRequest_Author {
	if t == nil {
		t = &GetPullRequestAuthor_Repository_PullRequest{}
	}
	return t.Author
}
func (t *GetPullRequestAuthor_Repository_PullRequest) GetTitle() string {
	if t == nil {
		t = &GetPullRequestAuthor_Repository_PullRequest{}
	}
	return t.Title
}

type GetPullRequestAuthor_Repository struct {
	PullRequest *GetPullRequestAuthor_Repository_PullRequest "json:\"pullRequest,omitempty\" graphql:\"pullRequest\""
}

func (t *GetPullRequestAuthor_Repository) GetPullRequest() *GetPullRequestAuthor_Repository_PullRequest {
	if t == nil {
		t = &GetPullRequestAuthor_Repository{}
	}
	return t.PullRequest
}

type GetPullRequestAuthor struct {
	Repository *GetPullRequestAuthor_Repository "json:\"repository,omitempty\" graphql:\"repository\""
}

func (t *GetPullRequestAuthor) GetRepository() *GetPullRequestAuthor_Repository {
	if t == nil {
		t = &GetPullRequestAuthor{}
	}
	return t.Repository
}

const GetPullRequestAuthorDocument = `query GetPullRequestAuthor ($owner: String!, $name: String!, $number: Int!) {
	repository(owner: $owner, name: $name) {
		pullRequest(number: $number) {
			title
			author {
				login
			}
		}
	}
}
`

func (c *Client) GetPullRequestAuthor(ctx context.Context, owner string, name string, number int, interceptors ...clientv2.RequestInterceptor) (*GetPullRequestAuthor, error) {
	vars := map[string]any{
		"owner":  owner,
		"name":   name,
		"number": number,
	}

	var res GetPullRequestAuthor
	if err := c.Client.Post(ctx, "GetPullRequestAuthor", GetPullRequestAuthorDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetPullRequestAuthorDocument: "GetPullRequestAuthor",
}
